parameters:
    nelmio_security.external_redirects.whitelist: ~

services:
    nelmio_security.external_redirect_listener:
        scope: request
        class: Nelmio\SecurityBundle\Listener\ExternalRedirectListener
        arguments:
            - %nelmio_security.external_redirects.abort%
            - %nelmio_security.external_redirects.override%
            - %nelmio_security.external_redirects.whitelist%
            - @?logger
            - @?router
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
            - { name: monolog.logger, channel: security }
